#ifndef SYMBOL_H
#define SYMBOL_H

#define LPAREN        "("
#define RPAREN        ")"
#define LBRACE        "["
#define RBRACE        "]"
#define LBRACKET      "{"
#define RBRACKET      "}"
#define NOT           "!"
#define DOT           "."
#define DOTDOT        ".."
#define SPREAD        "..."
#define PLUSPLUS      "++"
#define MINUSMINUS    "--"
#define QUESTION      "?"
#define MULTIPLY      "*"
#define DIVIDE        "/"
#define MODULO        "%"
#define PLUS          "+"
#define MINUS         "-"
#define SHIFT_LEFT    "<<"
#define SHIFT_RIGHT   ">>"
#define GREATER       ">"
#define LESS          "<"
#define GREATER_EQUAL ">="
#define LESS_EQUAL    "<="
#define EQUALTO       "=="
#define NOT_EQUALTO   "!="
#define BITWISE_AND   "&"
#define BITWISE_OR    "|"
#define BITWISE_XOR   "^"
#define AND           "&&"
#define OR            "||"
#define EQUAL         "="
#define COMMA         ","
#define SEMICOLON     ";"
#define COLON         ":"

#endif